import = [
    "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

[font]
size = 10

[font.normal]
family = "JetBrains Mono Nerd Font" # on linux
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[cursor.style]
blinking = "Always"
